#!/usr/bin/env bash

# ==============================================================================
# 99a-apps.sh - 安装官方仓库、AUR 和 Flatpak 应用
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ -f "$SCRIPT_DIR/00-utils.sh" ]]; then
  source "$SCRIPT_DIR/00-utils.sh"
else
  echo "Error: 00-utils.sh is not available in $SCRIPT_DIR."
  exit 1
fi

check_root

section "Phase 5" "Install common applications"

log "Identify the target user."
detect_target_user

if [[ -z "$TARGET_USER" || ! -d "$HOME_DIR" ]]; then
  error "The target user is not valid, or the home directory does not exist."
  exit 1
fi
info_kv "Target user" "$TARGET_USER"

LIST_FILENAME="common-applist.txt"
LIST_FILE="$PARENT_DIR/$LIST_FILENAME"
REPO_APPS=()
AUR_APPS=()
FLATPAK_APPS=()
FAILED_PACKAGES=()

if [[ ! -f "$LIST_FILE" ]]; then
  warn "$LIST_FILENAME is not available. Skip common applications."
  APP_LIST_RAW=""
elif ! grep -q -vE "^\s*#|^\s*$" "$LIST_FILE"; then
  warn "The application list is empty. Skip common applications."
  APP_LIST_RAW=""
else
  log "Read the application list from $LIST_FILENAME."
  APP_LIST_RAW=$(grep -vE "^\s*#|^\s*$" "$LIST_FILE" | sed -E 's/[[:space:]]+#/\t#/')
fi

while IFS= read -r line; do
  raw_pkg=$(echo "$line" | cut -f1 -d$'\t' | xargs)
  [[ -z "$raw_pkg" ]] && continue

  case "$raw_pkg" in
    flatpak:*) FLATPAK_APPS+=("${raw_pkg#flatpak:}") ;;
    AUR:*) AUR_APPS+=("${raw_pkg#AUR:}") ;;
    *) REPO_APPS+=("$raw_pkg") ;;
  esac
done <<<"$APP_LIST_RAW"

info_kv "Scheduled" "Repository: ${#REPO_APPS[@]}" "AUR/ArchLinuxCN: ${#AUR_APPS[@]}, Flatpak: ${#FLATPAK_APPS[@]}"

if [[ ${#REPO_APPS[@]} -gt 0 ]]; then
  section "Step 1/3" "Install repository packages"
  REPO_QUEUE=()
  for pkg in "${REPO_APPS[@]}"; do
    if pacman -Qi "$pkg" &>/dev/null; then
      log "$pkg is installed."
    else
      REPO_QUEUE+=("$pkg")
    fi
  done

  if [[ ${#REPO_QUEUE[@]} -gt 0 ]]; then
    info_kv "Install" "${#REPO_QUEUE[@]} pacman packages"
    if ! exe pacman -Syu --noconfirm --needed "${REPO_QUEUE[@]}"; then
      error "The repository package transaction failed."
      for pkg in "${REPO_QUEUE[@]}"; do
        FAILED_PACKAGES+=("repo:$pkg")
      done
    else
      success "The repository applications are installed."
    fi
  else
    success "All repository applications are already installed."
  fi
fi

TARGET_GROUP=$(id -gn "$TARGET_USER")

# Remove the installer generated by versions that deferred these applications
# until the first graphical login.
rm -f -- "$HOME_DIR/install_common_applist.sh" \
  "$HOME_DIR/install-common-applist-failures.txt"

if [[ ${#AUR_APPS[@]} -gt 0 ]]; then
  section "Step 2/3" "Install AUR and ArchLinuxCN applications"
  AUR_QUEUE=()
  for app in "${AUR_APPS[@]}"; do
    if pacman -Qi "$app" &>/dev/null; then
      log "$app is installed."
    else
      AUR_QUEUE+=("$app")
    fi
  done

  if [[ ${#AUR_QUEUE[@]} -gt 0 ]]; then
    if ! command -v paru >/dev/null 2>&1; then
      error "paru is not installed."
      for app in "${AUR_QUEUE[@]}"; do FAILED_PACKAGES+=("aur:$app"); done
    else
      PARU_MAKEPKG_ARGS=()
      if [[ -x "${SHORIN_MAKEPKG_WRAPPER:-}" ]]; then
        PARU_MAKEPKG_ARGS+=(--makepkg "$SHORIN_MAKEPKG_WRAPPER")
        log "Use the temporary GitHub Git/Curl routing for the Paru transaction."
      else
        warn "The temporary makepkg wrapper is unavailable; Paru will use the system configuration."
      fi

      as_user env PATH="$PATH" paru "${PARU_MAKEPKG_ARGS[@]}" \
        -Syu --noconfirm --needed "${AUR_QUEUE[@]}" || true
      for app in "${AUR_QUEUE[@]}"; do
        if ! pacman -Qi "$app" &>/dev/null; then
          FAILED_PACKAGES+=("aur:$app")
          rm -rf -- "$HOME_DIR/.cache/paru/clone/$app" "$HOME_DIR/.cache/paru/aur/$app"
        fi
      done
    fi
  else
    success "All AUR and ArchLinuxCN applications are already installed."
  fi
fi

if [[ ${#FLATPAK_APPS[@]} -gt 0 ]]; then
  section "Step 3/3" "Install Flatpak applications"
  FLATPAK_QUEUE=()
  for app in "${FLATPAK_APPS[@]}"; do
    if flatpak info --system "$app" &>/dev/null; then
      log "$app is installed."
    else
      FLATPAK_QUEUE+=("$app")
    fi
  done

  if [[ ${#FLATPAK_QUEUE[@]} -gt 0 ]]; then
    if ! flatpak remotes --system --columns=name 2>/dev/null | grep -Fxq flathub; then
      error "The system Flathub remote is unavailable."
      for app in "${FLATPAK_QUEUE[@]}"; do FAILED_PACKAGES+=("flatpak:$app"); done
    else
      flatpak install --system -y flathub "${FLATPAK_QUEUE[@]}" || true
      for app in "${FLATPAK_QUEUE[@]}"; do
        flatpak info --system "$app" &>/dev/null || FAILED_PACKAGES+=("flatpak:$app")
      done
    fi
  else
    success "All Flatpak applications are already installed."
  fi
fi

if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
  DOCS_DIR="$HOME_DIR/Documents"
  REPORT_FILE="$DOCS_DIR/installation-failures.txt"
  install -d -m 0755 -o "$TARGET_USER" -g "$TARGET_GROUP" "$DOCS_DIR"
  {
    printf '\n========================================================\n'
    printf ' Installation failure report - %s\n' "$(date)"
    printf '========================================================\n'
    printf '%s\n' "${FAILED_PACKAGES[@]}"
  } >>"$REPORT_FILE"
  chown "$TARGET_USER:$TARGET_GROUP" "$REPORT_FILE"
  error "Some repository applications failed to install. See $REPORT_FILE."
  exit 1
fi

log "Module 99a-apps is complete."
