#!/usr/bin/env bash

# ==============================================================================
# 99a-apps.sh - 安装官方仓库应用并生成用户应用安装脚本
# ==============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

if [[ -f "$SCRIPT_DIR/00-utils.sh" ]]; then
  source "$SCRIPT_DIR/00-utils.sh"
else
  echo "Error: 00-utils.sh is not available in $SCRIPT_DIR."
  exit 1
fi

check_root

section "Phase 5" "Install repository applications"

log "Identify the target user."
detect_target_user

if [[ -z "$TARGET_USER" || ! -d "$HOME_DIR" ]]; then
  error "The target user is not valid, or the home directory does not exist."
  exit 1
fi
info_kv "Target user" "$TARGET_USER"

LIST_FILENAME="common-applist.txt"
LIST_FILE="$PARENT_DIR/$LIST_FILENAME"
REPO_APPS=()
AUR_APPS=()
FLATPAK_APPS=()
FAILED_PACKAGES=()

if [[ ! -f "$LIST_FILE" ]]; then
  warn "$LIST_FILENAME is not available. Skip common applications."
  APP_LIST_RAW=""
elif ! grep -q -vE "^\s*#|^\s*$" "$LIST_FILE"; then
  warn "The application list is empty. Skip common applications."
  APP_LIST_RAW=""
else
  log "Read the application list from $LIST_FILENAME."
  APP_LIST_RAW=$(grep -vE "^\s*#|^\s*$" "$LIST_FILE" | sed -E 's/[[:space:]]+#/\t#/')
fi

while IFS= read -r line; do
  raw_pkg=$(echo "$line" | cut -f1 -d$'\t' | xargs)
  [[ -z "$raw_pkg" ]] && continue

  case "$raw_pkg" in
    flatpak:*) FLATPAK_APPS+=("${raw_pkg#flatpak:}") ;;
    AUR:*) AUR_APPS+=("${raw_pkg#AUR:}") ;;
    *) REPO_APPS+=("$raw_pkg") ;;
  esac
done <<<"$APP_LIST_RAW"

info_kv "Main install" "Repository: ${#REPO_APPS[@]}" "Deferred: AUR/ArchLinuxCN ${#AUR_APPS[@]}, Flatpak ${#FLATPAK_APPS[@]}"

if [[ ${#REPO_APPS[@]} -gt 0 ]]; then
  REPO_QUEUE=()
  for pkg in "${REPO_APPS[@]}"; do
    if pacman -Qi "$pkg" &>/dev/null; then
      log "$pkg is installed."
    else
      REPO_QUEUE+=("$pkg")
    fi
  done

  if [[ ${#REPO_QUEUE[@]} -gt 0 ]]; then
    info_kv "Install" "${#REPO_QUEUE[@]} pacman packages"
    if ! exe pacman -Syu --noconfirm --needed "${REPO_QUEUE[@]}"; then
      error "The repository package transaction failed."
      for pkg in "${REPO_QUEUE[@]}"; do
        FAILED_PACKAGES+=("repo:$pkg")
      done
    else
      success "The repository applications are installed."
    fi
  else
    success "All repository applications are already installed."
  fi
fi

DEFERRED_SCRIPT="$HOME_DIR/install_common_applist.sh"
TARGET_GROUP=$(id -gn "$TARGET_USER")

log "Generate the deferred user application installer."
# 清理由旧版脚本持久部署的代理 wrapper。首次登录后由用户自行处理网络环境。
OLD_HELPER_DIR="$HOME_DIR/.local/share/arch-niri-dms"
rm -f -- "$OLD_HELPER_DIR/curl-github-wrapper.sh" "$OLD_HELPER_DIR/git-github-wrapper.sh"
rmdir -- "$OLD_HELPER_DIR" 2>/dev/null || true

cat >"$DEFERRED_SCRIPT" <<'SCRIPT_HEADER'
#!/usr/bin/env bash

# Generated by arch-niri-dms. Safe to run again after a partial failure.
set -uo pipefail

if [[ $EUID -eq 0 ]]; then
  echo "Please run this script as your normal desktop user, not as root." >&2
  exit 1
fi

AUR_APPS=(
SCRIPT_HEADER
printf '  %q\n' "${AUR_APPS[@]}" >>"$DEFERRED_SCRIPT"
cat >>"$DEFERRED_SCRIPT" <<'SCRIPT_MIDDLE'
)
FLATPAK_APPS=(
SCRIPT_MIDDLE
printf '  %q\n' "${FLATPAK_APPS[@]}" >>"$DEFERRED_SCRIPT"
cat >>"$DEFERRED_SCRIPT" <<'SCRIPT_BODY'
)

failures=()

if [[ ${#AUR_APPS[@]} -gt 0 ]]; then
  if ! command -v paru >/dev/null 2>&1; then
    echo "Missing dependency: paru. Install it from the configured ArchLinuxCN repository:" >&2
    echo "  sudo pacman -S --needed paru" >&2
    failures+=("dependency:paru")
  else
    aur_queue=()
    for app in "${AUR_APPS[@]}"; do
      pacman -Qi "$app" &>/dev/null || aur_queue+=("$app")
    done

    if [[ ${#aur_queue[@]} -gt 0 ]]; then
      echo "Install ${#aur_queue[@]} deferred Paru packages with the user's current network configuration."
      paru -Syu --needed "${aur_queue[@]}" || true
      for app in "${aur_queue[@]}"; do
        if ! pacman -Qi "$app" &>/dev/null; then
          failures+=("aur:$app")
          rm -rf -- "$HOME/.cache/paru/clone/$app" "$HOME/.cache/paru/aur/$app"
        fi
      done
    else
      echo "All deferred Paru packages are already installed."
    fi
  fi
fi

if [[ ${#FLATPAK_APPS[@]} -gt 0 ]]; then
  if ! command -v flatpak >/dev/null 2>&1; then
    echo "Missing dependency: flatpak. Install it with:" >&2
    echo "  sudo pacman -S --needed flatpak" >&2
    failures+=("dependency:flatpak")
  else
    if ! flatpak remotes --user --columns=name 2>/dev/null | grep -Fxq flathub; then
      flathub_url=$(flatpak remotes --system --columns=name,url 2>/dev/null | awk '$1 == "flathub" { print $2; exit }')
      flathub_url=${flathub_url:-https://dl.flathub.org/repo/flathub.flatpakrepo}
      echo "Add the user-level Flathub remote: $flathub_url"
      if ! flatpak remote-add --user --if-not-exists flathub "$flathub_url"; then
        failures+=("config:flathub-user-remote")
      fi
    fi

    flatpak_queue=()
    for app in "${FLATPAK_APPS[@]}"; do
      flatpak info --user "$app" &>/dev/null || flatpak_queue+=("$app")
    done
    if [[ ${#flatpak_queue[@]} -gt 0 ]]; then
      echo "Install ${#flatpak_queue[@]} user-level Flatpak applications."
      flatpak install --user -y flathub "${flatpak_queue[@]}" || true
      for app in "${flatpak_queue[@]}"; do
        flatpak info --user "$app" &>/dev/null || failures+=("flatpak:$app")
      done
    else
      echo "All deferred Flatpak applications are already installed."
    fi
  fi
fi

if [[ ${#failures[@]} -gt 0 ]]; then
  report="$HOME/install-common-applist-failures.txt"
  printf '%s\n' "${failures[@]}" >"$report"
  echo "Some applications were not installed. See: $report" >&2
  exit 1
fi

rm -f "$HOME/install-common-applist-failures.txt"
echo "All deferred common applications are installed."
SCRIPT_BODY

chmod 0755 "$DEFERRED_SCRIPT"
chown "$TARGET_USER:$TARGET_GROUP" "$DEFERRED_SCRIPT"
success "Deferred installer created: $DEFERRED_SCRIPT"
warn "Run it as $TARGET_USER after the first desktop login to install Paru and Flatpak applications."

if [[ ${#FAILED_PACKAGES[@]} -gt 0 ]]; then
  DOCS_DIR="$HOME_DIR/Documents"
  REPORT_FILE="$DOCS_DIR/installation-failures.txt"
  install -d -m 0755 -o "$TARGET_USER" -g "$TARGET_GROUP" "$DOCS_DIR"
  {
    printf '\n========================================================\n'
    printf ' Installation failure report - %s\n' "$(date)"
    printf '========================================================\n'
    printf '%s\n' "${FAILED_PACKAGES[@]}"
  } >>"$REPORT_FILE"
  chown "$TARGET_USER:$TARGET_GROUP" "$REPORT_FILE"
  error "Some repository applications failed to install. See $REPORT_FILE."
  exit 1
fi

log "Module 99a-apps is complete."
